// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPV7ueegn0DMiHPT3Pfv-GjtI8iDRroJw',
    appId: '1:516718051322:web:5c9d56e06b50140db4ae43',
    messagingSenderId: '516718051322',
    projectId: 'select-project-77c47',
    authDomain: 'select-project-77c47.firebaseapp.com',
    storageBucket: 'select-project-77c47.firebasestorage.app',
    measurementId: 'G-HN8TLTSPTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbfBUPpmT9XD4f9sDBSxjNaFHaJmJo-Sg',
    appId: '1:516718051322:android:2f9bfa0e4cbc8f86b4ae43',
    messagingSenderId: '516718051322',
    projectId: 'select-project-77c47',
    storageBucket: 'select-project-77c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOBMigJgse65muPxx2yq1yi86qPSiIZV0',
    appId: '1:516718051322:ios:4eb638b520926956b4ae43',
    messagingSenderId: '516718051322',
    projectId: 'select-project-77c47',
    storageBucket: 'select-project-77c47.firebasestorage.app',
    iosBundleId: 'com.example.select',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOBMigJgse65muPxx2yq1yi86qPSiIZV0',
    appId: '1:516718051322:ios:4eb638b520926956b4ae43',
    messagingSenderId: '516718051322',
    projectId: 'select-project-77c47',
    storageBucket: 'select-project-77c47.firebasestorage.app',
    iosBundleId: 'com.example.select',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPV7ueegn0DMiHPT3Pfv-GjtI8iDRroJw',
    appId: '1:516718051322:web:2dbf1d24e228ab6bb4ae43',
    messagingSenderId: '516718051322',
    projectId: 'select-project-77c47',
    authDomain: 'select-project-77c47.firebaseapp.com',
    storageBucket: 'select-project-77c47.firebasestorage.app',
    measurementId: 'G-QWW3E7928Z',
  );
}
